" General stuff
set nocompatible     " vi can go to hell
syntax on            " Enable syntax highlighting
filetype off         " Disable filetype detection for vundle
set nostartofline    " Keep to current column when moving cursor
set hidden           " Allow multiple buffers
set encoding=utf-8   " Use UTF-8 encoding

" Indentation shit
set autoindent       " Preserve indent from previous line
set copyindent       " Copy indenting structure (tabs/spaces) from previous line
set preserveindent   " Preserve indentation structure when re-indenting line
set noexpandtab      " Hard tabs by default
set nosmarttab       " I like the idea of this, but it always seems to cause problems
set tabstop=3        " How many columns to display per tab
set shiftwidth=3     " The number of columns to re-indent by
set softtabstop=3    " The number of colums to insert for a tab

" Display stuff
set t_Co=256         " Enable 256 colours
set background=dark  " Blacker than the blackest black, times infinity
set number           " Line numbers
set ruler            " Show current position
set scrolloff=3      " Scroll before reaching the top/bottom of the window
set sidescrolloff=3  " Scroll before reaching the left/right of the window

" Search/autocomplete stuff
set hlsearch   " Highlight search results
set ignorecase " Enable case-insensitivity by default
set infercase  " Fix case when doing case-insensitive auto-complete
set smartcase  " Uppercase letters in search imply case-sensitivity
set incsearch  " Search as characters are typed

" Set backup/swap/undo file locations
" The trailing '//' causes vim to construct filenames from full paths
set backupdir=~/.vim/.backup//
set directory=~/.vim/.swap//
set undodir=~/.vim/.undo//

" Highlight column 81
" set colorcolumn=81
" highlight ColorColumn ctermbg=grey guibg=grey

" Retab macro
:command! -nargs=1 -range Retab <line1>,<line2>s/\v%(^ *)@<= {<args>}/\t/g

" Spellcheck macro
:command Spellcheck set spell spelllang=en

" Load modules
execute pathogen#infect()

" Pull crap in from plugins
filetype plugin indent on

" Enable detection for puppet plugin
let g:puppet_module_detect=1

" Airline
set laststatus=2
set noshowmode
set timeout ttimeoutlen=50
let g:airline_theme = "solarized"
let g:airline_powerline_fonts = 1 " Use powerline symbols

" Activate theme
colorscheme solarized

" Highlight trailing whitespace when exiting insert mode
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/
autocmd BufWinLeave * call clearmatches()
