### Theme
DEFAULT_USER=`whoami`
source  ~/.zsh/powerlevel9k/powerlevel9k.zsh-theme

### Spell-correction
setopt correct

### History
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=100000
setopt incappendhistory
setopt histignoredups
unsetopt sharehistory

# pushd settings
setopt pushdignoredups
unsetopt autopushd

### Generic environment
VIM_COMMAND="/usr/local/bin/mvim -v"
export EDITOR=$VIM_COMMAND
export GITEDITOR=$VIM_COMMAND
alias vim=$VIM_COMMAND
alias vi=$VIM_COMMAND

### Generic aliases
alias ls='ls -G'

### Completion
fpath=(/usr/local/share/zsh-completions $fpath)
autoload -Uz compinit
compinit

### Reverse search
bindkey -v
bindkey '^R' history-incremental-pattern-search-backward

### Plugins
source "/usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
#source "/usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh"

### Include misc config
ZSHRC_DIR="${HOME}/.zshrc.d"
if [ -d "${ZSHRC_DIR}" ]; then
	for rcfile in $ZSHRC_DIR/*.sh; do
		source $rcfile
	done
fi

### Include I2G-specific stuff, if available
[ -f $HOME/.zshrc.i2g ] && source $HOME/.zshrc.i2g
