# Theme
DEFAULT_USER=$(whoami)
POWERLEVEL9K_MODE="nerdfont-complete"
POWERLEVEL9K_HIDE_BRANCH_ICON=true
POWERLEVEL9K_FOLDER_ICON=""
POWERLEVEL9K_HOME_ICON=""
POWERLEVEL9K_HOME_SUB_ICON=""
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs time)

# Plugins
source "/usr/local/var/homebrew/linked/zplug/init.zsh"
zplug "bhilburn/powerlevel9k", use:powerlevel9k.zsh-theme
zplug "zsh-users/zsh-completions"
zplug "zsh-users/zsh-syntax-highlighting"
zplug load

# History
HISTFILE="$HOME/.zsh_history"
HISTSIZE=1000
SAVEHIST=1000
setopt BANG_HIST
setopt EXTENDED_HISTORY
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_FIND_NO_DUPS
setopt HIST_SAVE_NO_DUPS
setopt HIST_REDUCE_BLANKS
setopt HIST_VERIFY

# Neovim as vim
VIM_COMMAND="nvim"
export EDITOR=$VIM_COMMAND
export GITEDITOR=$VIM_COMMAND
alias vim=$VIM_COMMAND
alias vim=$VIM_COMMAND

# Fix delete key
bindkey '^[[3~'   delete-char
bindkey '^[[3;5~' delete-char

# CTRL+R for history search
autoload -Uz history-incremental-pattern-search-backward
bindkey '^R' history-incremental-pattern-search-backward

# Up/down for history navigation
autoload -Uz up-line-or-beginning-search down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
[[ -n "$key[Up]" ]] && bindkey -- "$key[Up]" up-line-or-beginning-search
[[ -n "$key[Down]" ]] && bindkey -- "$key[Down]" down-line-or-beginning-search

# Misc configs
ZSHRC_LOCAL="${HOME}/.zshrc.local"
if [[ -f "${ZSHRC_LOCAL}" ]]; then
	source "${ZSHRC_LOCAL}"
fi
