autoload -Uz compinit

### Theme
DEFAULT_USER=`whoami`
ZSH_THEME=agnoster

### Oh-my-zsh
ZSH="${HOME}/.zsh/oh-my-zsh/"
DISABLE_AUTO_UPDATE="true"
source "${ZSH}oh-my-zsh.sh"

### Spell-correction
setopt correct

### History
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=100000
setopt incappendhistory
setopt histignoredups
unsetopt sharehistory

# pushd settings
setopt pushdignoredups
unsetopt autopushd

### Generic environment
export EDITOR="/usr/bin/vim"

### Generic aliases
alias ls='ls --color=auto'
alias whois='whois -H'
alias s='ssh'
alias grep='ag --skip-vcs-ignores'
alias ack='ag --skip-vcs-ignores'
alias ag='ag --skip-vcs-ignores'

### Temporary (hopefully) vim aliases due to broken powerline package
export EDITOR="PYTHONPATH=/usr/lib/python3.3/site-packages /usr/bin/vim"
alias vim='PYTHONPATH=/usr/lib/python3.3/site-packages vim'
alias gvim='PYTHONPATH=/usr/lib/python3.3/site-packages gvim'

### Completion
compinit

### Syntax highlighting
source "${HOME}/.zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"

### Include misc config
ZSHRC_DIR="${HOME}/.zshrc.d"
if [ -d "${ZSHRC_DIR}" ]; then
	for rcfile in $ZSHRC_DIR/*.sh; do
		source $rcfile
	done
fi

### Include Anchor-specific stuff, if available
[ -f $HOME/.zshrc.anchor ] && source $HOME/.zshrc.anchor
